# -*- coding: utf-8 -*-
"""OpenCv (Image Colour change and Sketch+Cartoons) .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XGJv1Jq2RQQ5SXookOc0WWhrBhtzBFyW
"""

import cv2 
from matplotlib import pyplot as plt
from google.colab.patches import cv2_imshow

img = cv2.imread("plants.jpg")

img

gray=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

plt.imshow(gray,cmap='gray')

plt.title("Plants in B/W")

plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
plt.title("Plants Original")

imgC = cv2.stylization(img, sigma_s=150, sigma_r=0.25)  
cv2_imshow(imgC)  
cv2.waitKey()  
cv2.destroyAllWindows()

cartoon_image1, cartoon_image2  = cv2.pencilSketch(img, sigma_s=60, sigma_r=0.5, shade_factor=0.02)

cv2_imshow(cartoon_image1)  
cv2.waitKey()  
cv2.destroyAllWindows()

cv2_imshow(cartoon_image2)  
cv2.waitKey()  
cv2.destroyAllWindows()

invert = cv2.bitwise_not(gray)

img_blur = cv2.blur(invert, (10, 10))

def dodgeV2(image, mask):
    return cv2.divide(image, 255 - mask, scale=256)

final_img = dodgeV2(gray, img_blur)

cv2_imshow(final_img)

